TOOL_NAME="virtualbox"
TOOL_DESCRIPTION="Install VirtualBox"
TOOL_ALIASES="vbox"
TOOL_PLATFORMS="macos"
TOOL_DEPENDENCIES=""
TOOL_COMMANDS="install"

INSTALL_STRATEGY="dmg"
INSTALL_URL_MACOS="https://download.virtualbox.org/virtualbox/7.2.8/VirtualBox-7.2.8-173730-macOSArm64.dmg"
DMG_VOLUME_NAME="VirtualBox"
PKG_PATH="VirtualBox.pkg"

POST_INSTALL_MSG="VirtualBox installed"
