TOOL_NAME="xcode"
TOOL_DESCRIPTION="Install Xcode Command Line Tools"
TOOL_PLATFORMS="macos"
TOOL_DEPENDENCIES=""
TOOL_COMMANDS="install"

INSTALL_STRATEGY="os_command"
OS_COMMAND="sudo xcode-select --install"
